### ISSUE TITLE
returning current directory

### ISSUE THREAD

**Issue by NodeGuy** [sindresorhus/os-tmpdir#1]
It's returning the current directory for me instead of `/tmp` because of npm/npm#4531.

I don't know what the right thing to do here is but I know I don't want the current directory!  :-(

**Comment by sindresorhus** [comment]
I'm not sure what you're expecting here. This follows the node implementation. Should be opened [here](https://github.com/nodejs/io.js/issues/new) if it actually were an issue with the implementation, but it seems like it's expected behaviour.

**Comment by hillkim7** [comment]
If you use 'npm start' instead of 'node app.js' for executing your script, you get current directory from os.tmpDir().
