### ISSUE TITLE
Unnecessary constraint in package.json breaks dependencies in `node < 0.10`

### ISSUE THREAD

**Issue by grimen** [sindresorhus/os-tmpdir#2]
What is the point of dropping support for `v0.8`? Got dependency errors for the simplest library (that needs to work in legacy system running older Node.js environment) just because of one of the deps (`temp`) depends on `os-tmpdir`. See no reason to break it  - a mistake or by intention?

https://github.com/sindresorhus/os-tmpdir/blob/master/package.json#L13

**Comment by sindresorhus** [comment]
Node.js 0.8 is ancient and very few still support it. That being said, this should still work. You're probably just having problems with `^` versions. Make sure to upgrade npm to latest in your CI.

**Comment by grimen** [comment]
@sindresorhus Ancient but nothing much have happened with OS filesystems since Node 0.8, so therefore no point of locking it like that. Latest NPM not working no.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/os-tmpdir/blob/b2b1e366bb04a628372a0b86c271f4890b9b0527/package.json#L13 is not enforced and only result in a warning.
